%YAML:1.0 # need to specify the file type at the top!
# Stereo pair on x500_mono_cam; the folder name is legacy.

cam0:
  T_imu_cam:
    - [0.0, 0.0, 1.0, 0.12]
    - [-1.0, 0.0, 0.0, 0.035]
    - [0.0, -1.0, 0.0, 0.06]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps:
    - 1
  camera_model: pinhole
  distortion_coeffs:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  distortion_model: radtan
  intrinsics:
    - 539.936
    - 539.936
    - 640.0
    - 480.0
  resolution:
    - 1280
    - 960
  rostopic: /camera/image_raw
  timeshift_cam_imu: 0.0
cam1:
  T_imu_cam:
    - [0.0, 0.0, 1.0, 0.12]
    - [-1.0, 0.0, 0.0, -0.035]
    - [0.0, -1.0, 0.0, 0.06]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps:
    - 0
  camera_model: pinhole
  distortion_coeffs:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  distortion_model: radtan
  intrinsics:
    - 539.936
    - 539.936
    - 640.0
    - 480.0
  resolution:
    - 1280
    - 960
  rostopic: /camera1/image_raw
  timeshift_cam_imu: 0.0
